# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x12\x05image\"\x1a\n\x0cImageRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1c\n\rImageResponse\x12\x0b\n\x03url\x18\x01 \x01(\t2E\n\x0cImageService\x12\x35\n\x08GetImage\x12\x13.image.ImageRequest\x1a\x14.image.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=22
  _globals['_IMAGEREQUEST']._serialized_end=48
  _globals['_IMAGERESPONSE']._serialized_start=50
  _globals['_IMAGERESPONSE']._serialized_end=78
  _globals['_IMAGESERVICE']._serialized_start=80
  _globals['_IMAGESERVICE']._serialized_end=149
# @@protoc_insertion_point(module_scope)
